# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
windowrule = match:class discord, workspace 19 silent
windowrule = match:class org.mozilla.Thunderbird, workspace 20 silent
